feat: revert to old releaser (#10)
Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

diff --git a/.github/workflows/terraform-module.yaml b/.github/workflows/terraform-module.yaml
--- a/.github/workflows/terraform-module.yaml
+++ b/.github/workflows/terraform-module.yaml
@@ -1,15 +1,21 @@
-name: Terraform Module Validate
+name: Terraform Module
 on:
   pull_request:
+    types:
+      - opened
+      - reopened
+      - synchronize
+      - closed
+    branches:
+      - main
     paths:
       - modules/**
 permissions:
-  pull-requests: write
   contents: write
-
+  pull-requests: write
 jobs:
   find-changes:
-    name: Find changed Terraform modules
+    name: Find changes
     runs-on: ubuntu-latest
     outputs:
       changed-modules: ${{ steps.changed-modules.outputs.result }}
@@ -25,7 +31,7 @@ jobs:
         with:
           files_ignore: '.github/workflows/**'
 
-      - name: Get changed modules
+      - name: Get changed Terraform modules
         id: changed-modules
         uses: actions/github-script@v6.4.1
         with:
@@ -46,7 +52,7 @@ jobs:
             return uniqueModuleNames;
 
   update-readme:
-    name: Update README for ${{ matrix.module }}
+    name: ${{ matrix.module }} README.md update
     runs-on: ubuntu-latest
     needs: find-changes
     strategy:
@@ -66,10 +72,10 @@ jobs:
           output-file: README.md
           output-method: inject
           git-push: "true"
-          git-commit-message: auto update ${{ matrix.module }} README.md
+          git-commit-message: "chore(${{ matrix.module }}): auto update README.md"
 
   validate-module:
-    name: Validate ${{ matrix.module }}
+    name: ${{ matrix.module }} validate
     runs-on: ubuntu-latest
     needs: find-changes
     strategy:
@@ -86,3 +92,43 @@ jobs:
       - run: terraform init
       - run: terraform fmt -diff -check
       - run: terraform validate
+
+  release:
+    name: Release
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Terraform Module Releaser
+        uses: techpivot/terraform-module-releaser@v1
+
+  # This allows us to have a branch protection rule for jobs with matrix.
+  # Jobs without a matrix have been included to simplify configuration in
+  # GitHub settings
+  job-status:
+    name: Status
+    runs-on: ubuntu-latest
+    needs:
+      - release
+      - update-readme
+      - validate-module
+    if: always()
+    steps:
+      - name: Successful deploy
+        if: ${{ !(contains(needs.*.result, 'failure')) }}
+        run: |
+          echo "SUCCESS"
+          echo "======="
+          echo "This job is checked by GitHub branch protection to ensure matrix jobs have completed successfully."
+          echo "Success means all jobs have passed and a merge can happen."
+          exit 0
+      - name: Failing deploy
+        if: ${{ contains(needs.*.result, 'failure') }}
+        run: |
+          echo "FAILURE"
+          echo "======="
+          echo "This job is checked by GitHub branch protection to ensure matrix jobs have completed successfully."
+          echo "Failure means another job has failed and should be resolved before a merge can happen."
+          exit 1
+
